version: '3.4'
services:
  rasa:
    image: rasa-server-bot:latest
    build: "./"
    restart: always
    volumes:
    - ./data:/app/data
    - ./actions:/app/actions
    - ./models:/app/models
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    working_dir: /app
    ports:
    - '5005:5005'
    networks:
    - all

  rasa-actions:
    image: rasa-bot:latest
    build: "./"
    volumes:
    - ./actions:/app/actions
    # command: bash -c "rasa run actions"
    command: ["rasa","run","actions"]
    working_dir: /app
    restart: always
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"